(require 'cl)
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(setq package-enable-at-startup nil)
(package-initialize)

(setq dotfiles-packages-list
      '(ac-js2
        ac-slime
        ace-jump-mode
        ack-and-a-half
        async
        auctex
        auto-complete
        auto-complete-auctex
        auto-complete-nxml
        auto-complete-pcmp
        auto-indent-mode
        babel
        calfw
        column-enforce-mode
        company
        concurrent
        ctable
        dash
        deferred
        dired+
        direx
        discover
        eimp
        elisp-slime-nav
        enh-ruby-mode
        epc
        evil
        evil-god-state
        expand-region
        flymake-css
        flymake-easy
        flymake-haml
        flymake-python-pyflakes
        flymake-shell
        fringe-helper
        gh
        git-commit-mode
        git-gutter
        git-gutter-fringe
        git-rebase-mode
        google-translate
        goto-chg
        haml-mode
        helm
        helm-ack
        helm-swoop
        highlight-defined
        highlight-indentation
        highlight-symbol
        hlinum
        ht
        htmlize
        hungry-delete
        ibuffer-vc
        jedi
        jedi-direx
        js-comint
        js2-mode
        json-mode
        linum-relative
        log4e
        logito
        look-mode
        lusty-explorer
        mag-menu
        magit
        magit-commit-training-wheels
        magit-gh-pulls
        magit-push-remote
        makey
        markdown-mode
        mediawiki
        minimap
        mmm-mode
        multiple-cursors
        nodejs-repl
        org
        org-ac
        ox-html5slide
        pangu-spacing
        pcache
        pcre2el
        pcsv
        popup
        py-import-check
        python-environment
        python-info
        qml-mode
        rainbow-delimiters
        rainbow-mode
        shell-command
        simple-httpd
        skewer-mode
        slime
        slime-company
        smart-operator
        smart-tabs-mode
        splitter
        stylus-mode
        switch-window
        swoop
        sws-mode
        tern
        tern-auto-complete
        twittering-mode
        undo-tree
        visual-regexp
        visual-regexp-steroids
        vlf
        web-beautify
        web-mode
        xclip
        yagist
        yaml-mode
        yasnippet
        yaxception
        window-numbering
        zlc))

(defun dotfiles-auto-install-packages ()
  (package-refresh-contents)
  (mapc #'(lambda (package)
            (unless (package-installed-p package)
              (package-install package)))
        dotfiles-packages-list)
  (save-buffers-kill-emacs))

(dotfiles-auto-install-packages)
