;;kuanyui's ~/.emacs

;;掃描~/.emacs.d目錄
(add-to-list 'load-path "~/.emacs.d/rc")
(require 'rc-basic)
(require 'rc-programming)
(require 'rc-templates)
(require 'rc-edit)
(require 'rc-dired)
(require 'rc-ibuffer)
(require 'rc-eshell)

(require 'rc-gnus)
(require 'rc-twittering)
(require 'rc-magit)

(require 'rc-org)
(require 'rc-markdown)

(require 'rc-misc)
(require 'rc-private)

(require 'rc-python)
(require 'rc-haskell)
(require 'rc-ruby)
(require 'rc-perl)
(require 'rc-lisp)
(require 'rc-css)
(require 'rc-javascript)
(require 'rc-shell)
(require 'rc-qml)
(require 'rc-c)

(require 'rc-junk)

(require 'rc-site-lisp)

;;======================================================
;; customize 以下為Emacs自動生成，不要動
;;======================================================
;;

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("420efa03d9c9c519a4a7eca29918805387b8a7709e23b283f64a3163403e6b7d" "47160226d9b534d26067fcfb07f6bc1ea5922d9caafd29536c1a212e1cef571b" "7fde61efa16011b294db1448de9e0ae45d602ae949a640164bce6fece4420e90" "3f3410aaa7417bddb85bc29cadb34ccdcf579b2f4126d42d4bf07ef270d2fbba" "7ed6913f96c43796aa524e9ae506b0a3a50bfca061eed73b66766d14adfa86d1" "ea3f08f94c7732c63ffc601f5fcd2632d1b99f9195bf3b55f4710a37fd985d04" "dbfa6f95b6e56fb7b1592f610583e87ebb16d3e172416a107f0aceef1351aad0" "9ba004f6d3e497c9f38859ae263b0ddd3ec0ac620678bc291b4cb1a8bca61c14" "6aae982648e974445ec8d221cdbaaebd3ff96c3039685be9207ca8ac6fc4173f" default)))
 '(delete-selection-mode nil)
 '(guide-key-mode nil)
 '(helm-mode nil)
 '(mark-even-if-inactive t)
 '(newsticker-url-list
   (quote
    (("" "http://blog.vgod.tw/feed/?variant=zh-tw" nil nil nil)
     ("" "http://feeds.feedburner.com/xxddite" nil nil nil)
     ("" "http://m-miya.net/blog/feed" nil nil nil)
     ("" "http://www.twmemory.org/?feed=rss2" nil nil nil)
     ("" "http://nicechord.com/feed/" nil nil nil)
     ("" "http://feed.pixnet.net/blog/posts/rss/doki2014ex" nil nil nil)
     ("" "http://frontstreetman.blog.163.com/rss/" nil nil nil)
     ("" "http://artsierro.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://rail02000.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://fall-cicada.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://blog.cielazure.org/feed/" nil nil nil)
     ("" "http://feeds2.feedburner.com/pingveno" nil nil nil)
     ("" "http://inkwalk.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://artning2012.blog.fc2.com/?xml" nil nil nil)
     ("" "http://kokai543.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://timothylin1.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://blog.dr-hao.com/feeds/posts/default" nil nil nil)
     ("" "http://africadoctor.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://yoxem.github.io/atom.xml" nil nil nil)
     ("" "http://www.wmfield.idv.tw/feed" nil nil nil)
     ("" "http://feeds.feedburner.com/applemaru" nil nil nil)
     ("" "http://vinta.ws/blog/feed" nil nil nil)
     ("" "http://but.tw/feed/" nil nil nil)
     ("" "http://oiseaumer.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://www.tsundei.co.cc/feeds/posts/default" nil nil nil)
     ("" "http://1ining.tumblr.com/rss" nil nil nil)
     ("" "http://runawaylife.blog.shinobi.jp/RSS/" nil nil nil)
     ("" "http://feed.feedsky.com/heikezhi" nil nil nil)
     ("" "http://fredjame.com/rss" nil nil nil)
     ("" "http://atifans.net/feed/" nil nil nil)
     ("" "http://chenglap.com/posts.rss" nil nil nil)
     ("" "http://feeds.feedburner.com/DensetsuNoBasho" nil nil nil)
     ("" "https://www.byvoid.com/feed" nil nil nil)
     ("" "http://whiteeyeishere.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://feeds.feedburner.com/TypeIsBeautiful" nil nil nil)
     ("" "http://feeds.feedburner.com/Woohome" nil nil nil)
     ("" "http://blog.goo.ne.jp/urateco/rss2.xml" nil nil nil)
     ("" "http://www.architecturelover.com/feed/" nil nil nil)
     ("" "http://www.architizer.com/en_us/blog/feed/" nil nil nil)
     ("" "http://feeds.feedburner.com/AtGardenDesign" nil nil nil)
     ("" "http://blog.akanelee.me/posts.rss" nil nil nil)
     ("" "http://blog.evendesign.tw/rss" nil nil nil)
     ("" "http://nullprogram.com/blog/index.rss" nil nil nil)
     ("" "http://d.hatena.ne.jp/Nos/rss" nil nil nil)
     ("" "http://d.hatena.ne.jp/mhayashi1120/rss" nil nil nil)
     ("" "http://d.hatena.ne.jp/kiwanami/rss" nil nil nil)
     ("" "http://kotatu.org/blog/feed.xml" nil nil nil)
     ("" "http://coldnew.github.io/rss.xml" nil nil nil)
     ("" "http://yfwu.github.io/feed.xml" nil nil nil)
     ("" "http://www.pure-taiwan.info/feed" nil nil nil)
     ("" "http://steel1986.blog.fc2.com/?xml" nil nil nil)
     ("" "http://feeds.feedburner.com/Pansci" nil nil nil)
     ("" "http://www.chihchih.net/feeds/posts/default" nil nil nil)
     ("" "http://feed.pixnet.net/blog/posts/rss/maijonalisa" nil nil nil)
     ("" "http://shouhei-blog.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://feed.pixnet.net/blog/posts/rss/bourgogne" nil nil nil)
     ("" "http://www.wretch.cc/blog/ikai123&rss20=1" nil nil nil)
     ("" "http://blog.roodo.com/ato543/rss.xml" nil nil nil)
     ("" "http://www.femgeek.co.uk/feed/atom/" nil nil nil)
     ("" "http://www.gersonlab.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://lilylu59.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://lizclimo.tumblr.com/rss" nil nil nil)
     ("" "http://feed.pixnet.net/blog/posts/rss/hguuy" nil nil nil)
     ("" "http://d.hatena.ne.jp/Arufa/rss2" nil nil nil)
     ("" "http://www.bbc.co.uk/zhongwen/trad/index.xml" nil nil nil)
     ("" "http://zh.globalvoicesonline.org/hant/feed/" nil nil nil)
     ("" "http://globalvoicesonline.org/feed/" nil nil nil)
     ("" "http://world.yam.com/rss.php" nil nil nil)
     ("" "http://www.solidot.org/index.rss" nil nil nil)
     ("" "http://slashdot.jp/slashdotjp.rss" nil nil nil)
     ("" "http://blog.sina.com.tw/gorillastudio/feed.php?ver=rss&type=entry&blog_id=152" nil nil nil)
     ("" "http://tw.myblog.yahoo.com/a102579/rss" nil nil nil)
     ("" "http://marukitchen.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://blog.yorkxin.org/feed/" nil nil nil)
     ("" "http://ogc-daily.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://etoileos.com/feeds/news/atom/" nil nil nil)
     ("" "http://hongguofong.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://linux-cisco.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://pcmanx.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://tetralet.luna.com.tw/rss.php?blogId=1&profile=atom" nil nil nil)
     ("" "http://www.osnews.com/files/recent.xml" nil nil nil)
     ("" "http://tasuka.idv.tw/blog/rss.php" nil nil nil)
     ("" "http://zeroplex.blogspot.com/atom.xml" nil nil nil)
     ("" "http://feeds.feedburner.com/ijliao" nil nil nil)
     ("" "http://jiehan.org/feed/" nil nil nil)
     ("" "http://blog.snowtec.org/feed/" nil nil nil)
     ("" "http://pugs.blogs.com/audrey/atom.xml" nil nil nil)
     ("" "http://feeds.feedburner.com/chitsaou" nil nil nil)
     ("" "http://blog.gcos.me/atom.xml" nil nil nil)
     ("" "http://blog.longwin.com.tw/feed/" nil nil nil)
     ("" "http://blog.linux.org.tw/~jserv/index.rdf" nil nil nil)
     ("" "https://www.csslayer.info/wordpress/feed/" nil nil nil)
     ("" "http://feeds.feedburner.com/zespia" nil nil nil)
     ("" "http://ferrari.github.io/atom.xml" nil nil nil)
     ("" "http://feeds.feedburner.com/tzangms" nil nil nil)
     ("" "http://www.soimort.org/atom.xml" nil nil nil)
     ("" "http://ckhung0.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://jserv.logdown.com/posts.rss" nil nil nil)
     ("" "http://fcamel-life.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://ingramchen.io/feed.xml" nil nil nil)
     ("" "http://chomado.ciao.jp/feed/" nil nil nil)
     ("" "http://fuuzetsu.co.uk/blog/rss.xml" nil nil nil)
     ("" "http://coolshell.cn/feed" nil nil nil)
     ("" "http://www.metamuse.net/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://fred.ipod.to/blog/rss.php" nil nil nil)
     ("" "http://jetfire.posterous.com/rss.xml" nil nil nil)
     ("" "http://mykafkeasquelife.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://tiffanycmc.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://yiyeguan.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://prisoneroflife.wordpress.com/feed/" nil nil nil)
     ("" "http://feed.pixnet.net/blog/posts/rss/richter" nil nil nil)
     ("" "http://terrytai.com/rss.xml" nil nil nil)
     ("" "http://priv.tw/blog/feed/" nil nil nil)
     ("" "http://crazyskepticism.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://wensonyeh.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://isaacstn.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://chit-philosophy.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://www.ivanpig.com/blog/?feed=rss2" nil nil nil)
     ("" "http://tianchunbinghe.blog.163.com/rss/" nil nil nil)
     ("" "http://chochopk-zh-tw.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
     ("" "http://mypaper.pchome.com.tw/kuan0416/rss" nil nil nil)
     ("" "http://www.wretch.cc/blog/kuan0416&rss20=1" nil nil nil)
     ("" "http://mhperng.blogspot.com/feeds/posts/default" nil nil nil)
     ("" "http://chenglap-blog.logdown.com/posts.rss" nil nil nil))))
 '(org-agenda-files (quote ("~/org/agenda/Event.org" "~/org/agenda/Todo.org")))
 '(org-modules
   (quote
    (org-bbdb org-bibtex org-docview org-gnus org-habit org-info org-irc org-mhe org-rmail org-w3m)))
 '(resize-frame nil)
 '(safe-local-variable-values
   (quote
    ((pangu-spacing-real-insert-separtor . t)
     (pangu-spacing-mode . t))))
 '(scroll-bar-mode (quote right))
 '(transient-mark-mode 1)
 '(xclip-mode t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(put 'dired-find-alternate-file 'disabled nil)
 
