(
 (html-mode . ((css-indent-offset . 2) (js-indent-level . 2)))
 (js2-mode . ((js2-strict-missing-semi-warning . nil)
              (subdirs . t)
              (js-indent-level . 2)
              (css-indent-offset . 2)))
 (pug-mode . ((subdirs . t)
              (js-indent-level . 2)
              (css-indent-offset . 2)))
 (javascript-mode . ((subdirs . t)
                     (js-indent-level . 2)
                     (css-indent-offset . 2)))
 (mmm-mode . ((subdirs . t)
              (js-indent-level . 2)
              (css-indent-offset . 2)))
 (scss-mode . ((css-indent-offset . 2)))
 (mmm-mode . ((css-indent-offset . 2)))
 (org-mode . ((org-export-with-author . nil)
              (org-export-with-creator . nil)
              (org-export-with-date . nil)
              (org-export-with-email . nil)
              (org-export-with-title . nil)
              (org-export-with-section-numbers . nil)
              (org-export-time-stamp-file . nil)
              (org-export-with-latex . nil)
              (org-export-with-toc . nil)
              (org-html-head-include-default-style . nil)
              (org-html-head-include-scripts . nil)
              (org-html-preamble . nil)
              (org-html-postamble . nil)
              (org-html-mathjax-template . "")
              (org-html-infojs-template . "")
              (org-html-use-infojs . nil)
              (org-html-with-latex . nil)
              (org-html-toplevel-hlevel . 1)
              (org-html-style . "")
              (org-html-head . "")
              (org-html-allow-name-attribute-in-anchors . nil)
              ))
 )
